#!/usr/bin/env python
# VDSM REST API
# Copyright (C) 2011 Adam Litke, IBM Corporation
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public
# License along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA

import cherrypy
from Dispatcher import vdsm_cpDispatcher
import API

def start_server():
    cherrypy.server.socket_host = '0.0.0.0'
    d = vdsm_cpDispatcher()
    conf = { '/': {'request.dispatch': d}}
    cherrypy.tree.mount(API.Root(), '/vdsm-api', config=conf)
    cherrypy.quickstart()

def main():
    start_server()

if __name__ == '__main__':
    main()
